[[plugins]]
# 補完プラグイン。
repo = 'neoclide/coc.nvim'
merged = '0'
rev = 'release'
hook_add = '''
  set statusline^=%{coc#status()}
  set updatetime=300
  nmap <silent> [g <Plug>(coc-diagnostic-prev)
  nmap <silent> ]g <Plug>(coc-diagnostic-next)
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
  nmap <silent> <F2> <Plug>(coc-rename)
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
